"use client";

import React, { useEffect, useState, useCallback, useMemo, useRef } from "react";
import { useRouter } from "next/navigation";
import { useAuthContext } from "@/context/AuthContext";
import { useZones } from "@/lib/hooks/useZones";
import { useIncidents } from "@/lib/hooks/useIncidents";
import { translations } from "@/lib/translations";
import { useLanguage } from "@/context/LanguageContext";
import { IncidentRow } from "@/components/IncidentRow";
import { Button } from "@/components/ui/button";
import { doc, updateDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { OpsZoneTable } from "@/components/OpsZoneTable";
import { OpsAlertFeed, Alert } from "@/components/OpsAlertFeed";
import { OpsIncidentForm } from "@/components/OpsIncidentForm";

/** Aggregated metrics derived from zone data. */
interface LiveMetrics {
  avgOccupancy: number;
  warningCount: number;
  criticalCount: number;
  nominalCount: number;
  systemStatus: "NOMINAL" | "WARNING" | "CRITICAL";
}

/**
 * Computes aggregate metrics from the zones array.
 * @param zones - Array of zone objects with status and occupancy.
 * @returns Aggregated metrics including system-level status.
 */
function computeMetrics(zones: { occupancyPercent: number; status: string }[]): LiveMetrics {
  if (zones.length === 0) {
    return { avgOccupancy: 0, warningCount: 0, criticalCount: 0, nominalCount: 0, systemStatus: "NOMINAL" };
  }

  let total = 0;
  let warningCount = 0;
  let criticalCount = 0;
  let nominalCount = 0;

  for (const z of zones) {
    total += z.occupancyPercent;
    if (z.status === "CRITICAL") criticalCount++;
    else if (z.status === "WARNING") warningCount++;
    else nominalCount++;
  }

  const avgOccupancy = Math.round(total / zones.length);
  const systemStatus: LiveMetrics["systemStatus"] =
    criticalCount > 0 ? "CRITICAL" : warningCount > 0 ? "WARNING" : "NOMINAL";

  return { avgOccupancy, warningCount, criticalCount, nominalCount, systemStatus };
}

/** Status color map for the system status badge. */
const SYSTEM_STATUS_STYLES: Record<string, string> = {
  NOMINAL: "text-primary bg-primary-container/20 border-primary/30",
  WARNING: "text-tertiary bg-tertiary/20 border-tertiary/30",
  CRITICAL: "text-error bg-error/20 border-error/30 animate-pulse",
} as const;

export default function OpsDashboardPage() {
  const router = useRouter();
  const { language } = useLanguage();
  const t = translations[language] || translations.en!;

  const { user, loading: authLoading, isStaff } = useAuthContext();

  const { zones, loading: zonesLoading } = useZones();
  const { incidents, loading: incidentsLoading, logIncident } = useIncidents();

  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [generatingAlerts, setGeneratingAlerts] = useState(false);
  const [showLogForm, setShowLogForm] = useState(false);
  const [alertsLastUpdated, setAlertsLastUpdated] = useState<string | null>(null);

  /** Prevents double-firing of auto-generate on mount. */
  const hasAutoGenerated = useRef(false);

  // Authentication check redirection
  useEffect(() => {
    if (!authLoading) {
      if (!user || !isStaff) {
        router.replace("/");
      }
    }
  }, [user, authLoading, isStaff, router]);

  // Live aggregated metrics derived from real-time zone data
  const metrics = useMemo(() => computeMetrics(zones), [zones]);

  // Count unresolved incidents
  const unresolvedCount = useMemo(
    () => incidents.filter((inc) => !inc.resolvedAt).length,
    [incidents]
  );

  const handleGenerateAlerts = useCallback(async () => {
    if (!user) return;
    setGeneratingAlerts(true);
    try {
      const token = await user.getIdToken();
      const res = await fetch("/api/ops/alerts/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
      });

      if (!res.ok) throw new Error("Failed to generate alerts");

      const data = await res.json();
      const parsedAlerts = (data.alerts || []).map((a: Alert) => ({
        ...a,
        timestamp: "JUST NOW",
      }));
      setAlerts(parsedAlerts);
      setAlertsLastUpdated(new Date().toLocaleTimeString());
    } catch {
      // Fallback — keep existing alerts
    } finally {
      setGeneratingAlerts(false);
    }
  }, [user]);

  // Auto-generate alerts once zones are loaded and user is authenticated
  useEffect(() => {
    if (!hasAutoGenerated.current && user && isStaff && !zonesLoading && zones.length > 0) {
      hasAutoGenerated.current = true;
      handleGenerateAlerts();
    }
  }, [user, isStaff, zonesLoading, zones.length, handleGenerateAlerts]);

  const handleToggleIncidentStatus = useCallback(async (id: string, isResolved: boolean) => {
    try {
      const docRef = doc(db, "incidents", id);
      await updateDoc(docRef, {
        resolvedAt: isResolved ? new Date().toISOString() : null,
      });
    } catch {
      alert("Failed to toggle incident status");
    }
  }, []);

  const handleSubmitIncident = useCallback(async (
    zoneId: string,
    description: string,
    severity: "LOW" | "MEDIUM" | "HIGH"
  ) => {
    await logIncident(zoneId, description, severity);
    setShowLogForm(false);
  }, [logIncident]);

  const handleToggleForm = useCallback(() => {
    setShowLogForm((prev) => !prev);
  }, []);

  const handleCancelForm = useCallback(() => {
    setShowLogForm(false);
  }, []);

  if (authLoading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center min-h-[50vh] gap-3">
        <div className="w-8 h-8 rounded-full border-2 border-primary-container border-t-tertiary animate-spin" />
        <span className="font-data-mono text-xs text-on-surface-variant">VERIFYING OPERATOR CREDS...</span>
      </div>
    );
  }

  // Double check if redirect is happening
  if (!user || !isStaff) {
    return null;
  }

  return (
    <div className="flex-1 p-container-padding max-w-[1200px] mx-auto space-y-stack-gap pt-8 pb-32">
      {/* Header section */}
      <div className="flex flex-col md:flex-row md:justify-between md:items-end mb-grid-gutter gap-4">
        <div>
          <h1 className="font-headline-lg-mobile md:font-headline-lg text-2xl md:text-3xl text-on-surface font-extrabold tracking-tight">
            {t.incidentLog} Dashboard
          </h1>
          <div className="flex items-center gap-2 mt-1">
            <span className="font-data-mono text-xs text-on-surface-variant uppercase tracking-wider">
              SYSTEM STATUS:
            </span>
            <span className={`inline-flex items-center px-2 py-0.5 rounded font-label-bold text-[10px] border uppercase tracking-wider ${SYSTEM_STATUS_STYLES[metrics.systemStatus] || ""}`}>
              {metrics.systemStatus}
            </span>
          </div>
        </div>
        <div className="flex gap-2">
          <Button
            variant="secondary"
            onClick={handleGenerateAlerts}
            disabled={generatingAlerts}
            className="flex items-center gap-2 h-touch-target-min font-label-bold text-xs"
          >
            <span className="material-symbols-outlined">psychology</span>
            {generatingAlerts ? "Analyzing..." : "Generate AI Alerts"}
          </Button>
          <Button
            variant="default"
            onClick={handleToggleForm}
            className="flex items-center gap-2 h-touch-target-min font-label-bold text-xs"
          >
            <span className="material-symbols-outlined">add_alert</span>
            Report Incident
          </Button>
        </div>
      </div>

      {/* Live Metrics Ribbon */}
      <section className="grid grid-cols-2 md:grid-cols-5 gap-4 border border-outline-variant/30 rounded-xl bg-[#1A1C1E] p-4">
        <div className="flex flex-col gap-0.5">
          <span className="font-data-mono text-[10px] text-on-surface-variant uppercase tracking-wider">
            AVG OCCUPANCY
          </span>
          <span className="font-headline-lg text-xl text-tertiary font-extrabold">
            {metrics.avgOccupancy}%
          </span>
        </div>
        <div className="flex flex-col gap-0.5">
          <span className="font-data-mono text-[10px] text-on-surface-variant uppercase tracking-wider">
            NOMINAL ZONES
          </span>
          <span className="font-headline-lg text-xl text-primary font-extrabold">
            {metrics.nominalCount}
          </span>
        </div>
        <div className="flex flex-col gap-0.5">
          <span className="font-data-mono text-[10px] text-on-surface-variant uppercase tracking-wider">
            WARNING ZONES
          </span>
          <span className="font-headline-lg text-xl text-tertiary font-extrabold">
            {metrics.warningCount}
          </span>
        </div>
        <div className="flex flex-col gap-0.5">
          <span className="font-data-mono text-[10px] text-on-surface-variant uppercase tracking-wider">
            CRITICAL ZONES
          </span>
          <span className="font-headline-lg text-xl text-error font-extrabold">
            {metrics.criticalCount}
          </span>
        </div>
        <div className="flex flex-col gap-0.5">
          <span className="font-data-mono text-[10px] text-on-surface-variant uppercase tracking-wider">
            OPEN INCIDENTS
          </span>
          <span className="font-headline-lg text-xl text-error font-extrabold">
            {unresolvedCount}/{incidents.length}
          </span>
        </div>
      </section>

      {/* Report Incident Modal/Collapse Form */}
      {showLogForm && (
        <OpsIncidentForm
          zones={zones}
          onSubmit={handleSubmitIncident}
          onCancel={handleCancelForm}
        />
      )}

      {/* Bento Grid Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-grid-gutter">
        <OpsZoneTable
          zones={zones}
          loading={zonesLoading}
          translations={t}
        />

        <OpsAlertFeed
          alerts={alerts}
          translations={t}
          lastUpdated={alertsLastUpdated}
        />
      </div>

      {/* Incident Log list */}
      <section className="bg-[#1A1C1E] border border-outline-variant/30 rounded-xl p-4 mt-6">
        <div className="flex justify-between items-center mb-4 border-b border-outline-variant/30 pb-2">
          <h3 className="font-headline-lg-mobile text-lg font-bold text-on-surface uppercase tracking-tight">
            {t.incidentLog}
          </h3>
          <span className="font-data-mono text-xs text-on-surface-variant">
            {unresolvedCount} UNRESOLVED / {incidents.length} TOTAL
          </span>
        </div>

        {incidentsLoading ? (
          <div className="py-8 flex justify-center">
            <div className="w-6 h-6 rounded-full border-2 border-primary-container border-t-tertiary animate-spin" />
          </div>
        ) : (
          <div className="space-y-2 max-h-[350px] overflow-y-auto no-scrollbar">
            {incidents.length === 0 ? (
              <p className="text-xs text-on-surface-variant font-data-mono py-4 text-center">
                NO ACTIVE SECURITY EVENTS REPORTED
              </p>
            ) : (
              incidents.map((incident) => (
                <IncidentRow
                  key={incident.id}
                  incident={incident}
                  onToggleStatus={handleToggleIncidentStatus}
                />
              ))
            )}
          </div>
        )}
      </section>
    </div>
  );
}
